### PR TITLE
Match routes by order (WIP)

### LINKED ISSUE #2: findDOMNode is deprecated
Hi there, @nanxiaobei !
First off, let me congratulate you for this awesome small tool you've developed! It's neat and simple to use.

So far I've found only 1 small issue. It seems the "findDOMNode" method [is being deprecated by the React team](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage), in favor of using a direct ref to the element you want to reference, as you can see in the example on that URL.

If you are developing a React app in "Strict Mode" like me, you will be getting a console error when switching from route to route (only the first time):
image

It sounds like it would be easy to fix, but I don't know. I thought it would be worth just mentioning it.

Cheers

### LINKED ISSUE #14: Animation does not work with nested pages from 2nd level onwards.
Hi,
Animation does not work with nested pages from 2nd level onwards for example I have a journey:

Home > Page 1 > Page 5 > Page 6
Home > Page 3
Home > Page 4

and my router looks like:

<SlideRoutes>
    <Route path="/home" element={<Page1 />} exact />
    <Route path="/page1" element={<Page1 />} exact />
    <Route path="/page2" element={<Page1 />} exact />
    <Route path="/page3" element={<Page1 />} exact />
    <Route path="/page4" element={<Page1 />} exact />
    <Route path="/page5" element={<Page1 />} exact />
    <Route path="/page6" element={<Page1 />} exact />
</SlideRoutes>

Here:
- Home calls Page 1 via useNavigate()
- Page 1 calls Page 5 via useNavigate()
- page 5 calls Page 6 via useNavigate()

- Home calls Page 2 via useNavigate()
- Home calls Page 3 via useNavigate()

Animation only works between:

- Home > Page 1
- Home > Page 2
- Home > Page 3

Animation does not work for the second level of the journey onwards

### LINKED ISSUE #23: More flexible route order
In #22, I wanted to add a way for users to control route order that doesn't rely on a static `pathList`.

There's a few considerations here:

1. React router allows to generate content dynamically, therefore it might not be possible (or be very memory heavy) to create a static path list
2. The order of `Route`s has semantic meaning (the first matching one is rendered). I think my PR matches this behavior, so it should always look correct. Might need some unit tests
3. `react-router` has some additional code for nested routes that I didn't replicate in the PR. That needs to be added to work correctly when using `SlideRoutes` nested under another `*Routes` component
4. There's the case that the matched route indices are equal when navigating between two locations that are matched by the same route. My PR didn't handle that case, but we should either allow to specify an undirected transition for that case it just do none instead of an arbitrary directed one.

Also we could allow people to customize transition direction order on top of all that. I'd imagine a function with a signature like the `compareFn` argument of [Array.prototype.sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort).

### PR DESCRIPTION
**Pull request by flying-sheep**
New attempt for #22.

- [x] Default to route definition order and add a way to customize order. Fixes #23
- [x] Handle nested usage. Fixes #14
- [x] Allow using in React 18’s `StrictMode` without warnings. Fixes #2

### CODE REVIEW

**Comment by nanxiaobei** [comment]
`3.0.0` is released and included these features.

**Comment by flying-sheep** [comment]
awesome!

**Comment by ehauner** [comment]
@flying-sheep can you provide an example of how to use nested `SlideRoutes` components? I saw your example above with `createElement` and that works but how would this look using more conventional React syntax? I get errors trying to nest `Routes` components like this (pseudocode):

```
<BrowserRouter>
    <Routes>
        <Route />
        <Route />
        <Route>
            <SlideRoutes>
                <Route />
                <Route />
            </SlideRoutes>
        </Route>
    </Route>
</BrowserRouter>
```

Here is a CodeSandbox example showing the error message https://codesandbox.io/s/react-slide-routes-forked-jy22jr?file=/src/App.js

**Comment by flying-sheep** [comment]
You need to use `element` instead of `children`: https://codesandbox.io/s/react-slide-routes-forked-yh34fr?file=/src/App.js

```jsx
<SlideRoutes>
  <Route
    path="/*"
    element={
      <SlideRoutes>
        <Route path="home" element={<Home />} />
        <Route path="about" element={<About />} />
        <Route path="contact" element={<Contact />} />
      </SlideRoutes>
    }
  />
  <Route path="foo" element={<p>foo</p>} />
</SlideRoutes>
```

**Comment by ehauner** [comment]
@flying-sheep thank you! That works perfectly. I tried something similar earlier but I didn't have the asterisk in the parent's path so I thought it didn't work.

**Pull request merged**
