### PR TITLE
Match routes instead of manually using `pathList`

### PR DESCRIPTION
**Pull request by flying-sheep**
I did the following. Check out the individual commits for the three parts (I cleaned them up so they each mostly have one purpose)

1. Switched to TypeScript
2. Added a demo file `index.html` (we can remove or move that one e.g. to `/demo` or so). Use `yarn start` to concurrently run `rollup --watch` and `serve -s` for trying out things.
3. Got rid of all complex mount/cache/queue logic. I replaced it with some simple code using `matchRoutes`:

   https://github.com/nanxiaobei/react-slide-routes/blob/46c2922a7b565a64d9c9060fdced920fb9a734a9/src/index.tsx#L152-L160

   https://github.com/nanxiaobei/react-slide-routes/blob/46c2922a7b565a64d9c9060fdced920fb9a734a9/src/index.tsx#L127-L131

The only thing that’s not ideal yet (IMHO) is that the tarball contains `dist/rollup.config.d.ts` and `dist/src/index.d.ts` instead of just `dist/index.d.ts`. Just a minor cosmetic thing though.

### CODE REVIEW

**Comment by nanxiaobei** [comment]
Sorry, the change is too big to accept at present.

**Comment by flying-sheep** [comment]
Makes sense, but it's a large step forward for this component. Gets rid of a bunch if complexity while adding functionality.

If you don't want that, I guess I have to fork this component and publish it under a different name. Which is a shame since small projects like this are hard enough to find already.

**Comment by nanxiaobei** [comment]
`2.2.0` is updated to typescript version. I wonder if you'd like to make another PR based on `2.2.0`.
I'll accept the PR and do some test & small edits, thanks.

**Comment by flying-sheep** [comment]
Thank you!

One thing I forgot to mention is that this PR allows to use `Route`s that have `element="a string"` or `element={null}` without crashing.

I like TypeScript because it allows to find bugs like this without writing unit tests or manually testing things.

**Pull request closed without merging**
